spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/purchases
    username: postgres
    password: example
  jpa:
    hibernate:
      ddl-auto: create-drop
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: purchase-group-id-1

kafka-topic: purchase-topic